### ISSUE TITLE
Simplify YAML syntax

### ISSUE THREAD

**Issue by markcoletti** [markcoletti/gremlin#1]
The YAML grammar for Gremlin can be simplified.  E.g., given the current example of a Gremlin YAML configuration file:

```yaml
evolution:
    name: leap_ec.algorithm.generational_ea *or* custom_generator_function
    params:
        max_generations: 50
        pop_size: 25
        problem:
            name: leap_ec.problem.Problem *or* custom_class
            params:
                maximize: False
        representation:
            name: leap_ec.representation.Representation *or* custom_class
            params:
                initialize:
                    name: curried_initializer_function (see leap_ec.int_rep.create_int_vector)
                    params: {}
analysis:
    name: analysis_function
```

All the `params` statements can be removed as the rest of the statements can be inferred as being parameters for the entity in which they're nested.

**Comment by markcoletti** [comment]
Another simplification: require users to roll the initializer and decoder into a `Representation` subclass and then specify _that_ in the YAML config file.

**Comment by markcoletti** [comment]
Also, maybe just assume a by-generation approach with an added issue to optionally override that with, say, an asynchronous EA.

**Comment by markcoletti** [comment]
First cut of revamped `config.yml`:

```yaml
# Gremlin config file for MNIST example
#
# Usage:
#     $ gremlin.py config.yml

pop_size: 50
max_generations: 30
problem: problem.MNIST_Problem
representation: representation.MNIST_Representation
```
