### ISSUE TITLE
Make importing more flexible

### ISSUE THREAD

**Issue by markcoletti** [markcoletti/gremlin#19]
Currently config file `import` sections will import just modules; however sometimes we want to use the `from <foo> import` style, which is not supported.  It would be more flexible and intuitive if there was a general preamble section that allowed for imports and general executable code.

**Comment by markcoletti** [comment]
I'm wanting to do more than just make importing more flexible -- I also want to allow for specialized code, such as functions, that can be referred to in the config file specified LEAP pipeline. E.g., I may want to define a pipeline operator before defining the pipeline, as I would need to do to resolve, say, partial function effects beforehand.

**Comment by markcoletti** [comment]
Replace `imports` in config file with `preamble`.  E.g.,:

```yaml
preamble: |
    import re
    from pathlib import Path

    def foo():
        pass
```

**Comment by markcoletti** [comment]
Now the MNIST example `config.yaml` looks like this:

```yaml
pop_size: 7
algorithm: bygen
bygen: # parameters that only make sense for a by-generation EA
  max_generations: 5
  k_elites: 2 # optional parameter for specifying the number (k) elites we keep per generation
problem: problem.MNISTProblem()
representation: representation.MNISTRepresentation()
pop_file: pop.csv # where we will write out each generation in CSV format
preamble: |
  import probe # need to import our probe.py so that LEAP sees our probe pipeline operator
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - ops.evaluate
  - probe.IndividualProbeCSV('inds.csv') # our own probe to see every single created offspring
  - ops.pool(size=${pop_size})
```
