### ISSUE TITLE
Allow for defining dask clients in preamble

### ISSUE THREAD

**Issue by markcoletti** [markcoletti/gremlin#21]
There are a variety of distributed dask client types.  It would greatly enhance Gremlin if we could define a dask client in the preamble to be used for defining cluster configurations.  E.g., we could define a `SSHCluster` or `PBSCluster` client in the preamble that Gremlin would use.

**Comment by markcoletti** [comment]
As an example, would like to support [SSHCluster](https://docs.dask.org/en/stable/deploying-ssh.htmll).

**Comment by markcoletti** [comment]
What's going to have to happen:

1. The users defines a Dask client using the `client` or other "well-known" variable name, such as `dask_client`; essentially adding a kind of new keyword that cannot be used for any other purpose but for defining a Dask client.
2. Gremlin detects this variable and switches to use that instead of the current locally defined Dask client.

**Comment by markcoletti** [comment]
What I've done is made a separate `distributed` YAML config section that looks like this:


```yaml
distributed:
  with_client: |
    client.wait_for_workers(1)
    print('We have at least one workers, so proceeding.')
  client: Client(LocalCluster(n_workers=multiprocessing.cpu_count(),
                               threads_per_worker=1,
                               processes=True,
                               silence_logs=logger.level)) # default to using all local cores

```

So any ole Dask client can be assigned to `distributed.client`. Moreover, you can use this to assign a `scheduler_file` if you want to distribute across systems, like on Summit or a local cluster.

**Comment by markcoletti** [comment]
That type of Dask information would normally only be associated with `async` runs, but I've also added optional support for the `bygen` mode of Gremlin to use Dask.

So here is the `bygen` config:
```yaml
algorithm: bygen
bygen: # parameters that only make sense for a by-generation EA
  max_generations: 5
  k_elites: 2 # optional parameter for specifying the number (k) elites we keep per generation

pop_file: pop.csv # where we will write out each generation in CSV format

pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - ops.evaluate
  - probe.IndividualProbeCSV('inds.csv') # our own probe to see every single created offspring
  - ops.pool(size=${pop_size})
```

You can override the pipeline for async support using this additional config YAML:

```yaml
pipeline:
  - ops.tournament_selection
  - ops.clone
  - mutate_randint(expected_num_mutations=1, bounds=representation.MNISTRepresentation.genome_bounds)
  - synchronous.eval_pool(client=client, size=len(parents))
```

Essentially the evaluation and pooling have been consolidated into a single pipeline operator, `synchronous.eval_pool`, that fans out all the offspring to be evaluated with the given Dask client.  `client` will be the one set in `distributed.client`.
